### ISSUE TITLE
User feedback 1

### ISSUE THREAD

**Issue by LottaMe** [LottaMe/pylet#62]
## Notes to first batch of user interview
_There were two interviews, with sitting next to the person using the application and watching their interaction followed by clarifying questions afterwards. 
There were two interviews after sending the person the repository and giving them time to try it out._

- After initial understanding, good progress.
    - Initial understanding is not as clear as it should be. Documentation needs to be clearer, first exercise should also explain more.
- Most exercises are intuitive with some exceptions
- Success & error messages are not sufficient
    - Different messages for test and exercises
    - Success message(s) should mention # I AM NOT DONE comment
- Specific exercise feedback:
    - Variables3:
        - Unintuitive why variable has to be redefined. Is there a way to write this exercise, so it is using an actual reason to redefine the variable and not just to get a test to pass
    - Basic types 3 and 4  got especially good feedback
    - Functions 3 and 4 can be improved, but are ok
    - Classes exercise to demonstrate the diamond problem might be nice
- Ending course is anti-climactic 

## TODOs from first batch of user interviews:

- [x] Update Documentation: It should explain more that you are supposed to solve the exercises in the exercise files and see the result in the terminal
- [x] First exercise: Should tell user to go to exercise to adjust the code. Should say that the code is already running successfully, but that you need to remove the # I AM NOT DONE comment
- [x] Adjust success and failure messages
    - [x] Rename error to failure message
    - [x] Messages should have different flavor for exercises that fail to execute and exercise that fail tests
    - [x] Success message should have comment to remove # I AM NOT DONE comment to continue
- [x] Change exercises:
    - [x] Variables3
    - [x] Add diamond problem exercise
- [x] Add more fun finish message
